### ISSUE TITLE
How can I apply obfuscation to my AAR

### ISSUE THREAD

**Issue by accuware** [blundell/release-android-library#14]
...is this possible at all?

**Comment by blundell** [comment]
Thats not something this release script will do sorry.

There are some post-processes you can do in proguard though

https://www.guardsquare.com/en/proguard/manual/examples#library

GoodLuck

**Comment by accuware** [comment]
Wow, you are fast :) Thanks, figured it out by myself currently.

**Comment by xrigau** [comment]
If you're publishing a library, you should use the `consumerProguardFiles` method to specify the proguard options that will be used when someone obfuscates a project that uses your library, since you can't/shouldn't proguard an aar artifact

More info: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:consumerProguardFiles

https://stackoverflow.com/questions/41572630/consumerproguardfiles-vs-proguardfiles
